# Generated by Django 4.0.4 on 2022-04-21 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list = []

    operations = [
        migrations.CreateModel(
            name="Specs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=10)),
                ("fuel_type", models.CharField(max_length=10)),
                ("max_speed", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                ("previous_owner", models.CharField(max_length=30, null=True)),
                (
                    "date_imported",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "specs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.specs",
                    ),
                ),
            ],
        ),
    ]
